### PR TITLE
Add handling if modDirectory is null (edgecase)

### PR DESCRIPTION
**Pull request by ttr**
... also, linter did it's thing.

### CODE REVIEW

**Comment by Erdroy** [comment]
I'm just thinking if... maybe we should just use a `continue;` keyword there?

**Comment by ttr** [comment]
You could, but break is ok in this scenario as You're doing similar in next step:
```
            var contentDirectory = Path.Combine(modDirectory, "Content");

            // Skip if this mod does not have any custom content
            if (!Directory.Exists(contentDirectory))  yield break;
```
instead this PR you could do:
```
            if (modDirectory == null) {yield break;}
            var contentDirectory = Path.Combine(modDirectory, "Content");

            // Skip if this mod does not have any custom content
            if (!Directory.Exists(contentDirectory))  yield break;            
```

just IMO this would be unnecessary call to LoadBundleFromModDirectory to bail out.

**Comment by ttr** [comment]
uh..
unless you're thinking about continue to not break foreach loop... yeah.

so:
```
            foreach (var itemWrap in result)
            {
                var modDirectory = itemWrap.DirectoryPath;
                if (modDirectory == null) {
                    AddonsLogger.Warning($"Missing mod directory for mod with id={itemWrap.Id}");
                    continue;
                }
                yield return LoadBundleFromModDirectory(modDirectory);
            }
```

**Comment by Erdroy** [comment]
> uh.. unless you're thinking about continue to not break foreach loop... yeah.
> 
> so:
> 
> ```
>             foreach (var itemWrap in result)
>             {
>                 var modDirectory = itemWrap.DirectoryPath;
>                 if (modDirectory == null) {
>                     AddonsLogger.Warning($"Missing mod directory for mod with id={itemWrap.Id}");
>                     continue;
>                 }
>                 yield return LoadBundleFromModDirectory(modDirectory);
>             }
> ```

Yes, exactly. If you could make a commit with this, I'll merge this

**Review by Erdroy — APPROVED** [review]
LGTM :)

**Pull request merged**
